application: vitgaetest1
version: 1
runtime: python
api_version: 1

handlers:
- url: /crossdomain.xml
  static_files: files/crossdomain.xml
  upload: files/crossdomain.xml

- url: /assets
  static_dir: files

- url: .*
  script: main.py
