application: vitgaetest1
version: 1
runtime: python
api_version: 1

handlers:
- url: /crossdomain.xml
  static_files: files/crossdomain.xml
  upload: files/crossdomain.xml

- url: /assets
  static_dir: files

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /install
  script: install.py
  login: admin

- url: .*
  script: main.py
