--- !ditz.rubyforge.org,2008-03-06/project 
name: flexproxy
version: "0.4"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: flexproxy
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-08-20 16:18:14.326855 Z
    - Robert Sanders <rsanders+flexproxy@gmail.com>
    - created
    - basic functionality
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.2"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-08-20 16:18:31.302323 Z
    - Robert Sanders <rsanders+flexproxy@gmail.com>
    - created
    - feature upgrades, including cookies and APP keys
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.3"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-08-20 16:19:10.289989 Z
    - Robert Sanders <rsanders+flexproxy@gmail.com>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.4"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-08-20 16:20:02.548428 Z
    - Robert Sanders <rsanders+flexproxy@gmail.com>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.5"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-08-20 22:10:11.657054 Z
    - Robert Sanders <rsanders+flexproxy@gmail.com>
    - created
    - ""
